- Gruntfile.js
- Procfile
- package.json
- web.js
Estos cambios tienen por objetivo el poder **desplegar exitosamente la aplicación en Heroku**, para un futuro *despliegue automático* luego de cada cambio. Para esto, se ha hecho uso del [**buildpack Yo Angular**](https://github.com/nknj/heroku-buildpack-yo-angular) de Heroku.
Generalmente, los tutoriales y documentación referida al despliegue en Heroku de aplicaciones AngularJS hacen uso de **añadir la carpeta ```dist``` al control de versionado**, para que sea servida estáticamente por Heroku. Un ejemplo de este método puede encontrarse en [Deploying a Yeoman/Angular app to Heroku](http://www.sitepoint.com/deploying-yeomanangular-app-heroku/). Sin embargo, los archivos de este directorio no deberían ser agregados al repositorio, ya que **son archivos generados** y todo cambio mediante …
> Configuración de aplicación para el despliegue en Heroku

- bower.json
Debido a un error en **Grunt** **[1]**, el uso de una versión de Bootstrap posterior a ```3.3.4``` produce que ```grunt serve``` no incluya las hojas de estilo de Bootstrap en la aplicación. Por esto, se especifica la instalación de Bootstrap ```3.3.4``` en el archivo ```bower.json```.
**[1]** https://github.com/yeoman/generator-angular/issues/1116
> Utilización de Bootstrap v3.3.4

- package.json
Se especifican como ```dependencies``` (no ```devDependencies```) los paquetes necesarios para **ejecutar** la aplicación. Este cambio tiene por objetivo solucionar el error existente en *Heroku*, y que la interfaz se despliegue correctamente.
Los paquetes especificados son los utilizados por el script ```web.js```.
> Especificación de dependencias para la ejecución

- app/styles/main.css
Se refiere a que la barra verde en la que están los links arriba de la página se ve siempre cuando scrolleas!.. anteriormente se le superponian cosas
> Se ve siempre encima la barra de navegación de la página

- .slugignore
- app/index.html
Se hace uso de la versión **minificada** de *Font-Awesome*, y se añade al ```slugignore``` la versión completa del CSS. De esta manera, se trata de evitar el error producido por **Heroku**, al alcanzar el tiempo máximo de compilación debido a la ejecución de ```htmlmin```.
> Corrección de error en compilador Slug, por Font-Awesome

- app/scripts/controllers/analysis-new.js
- app/views/partials/analysis-addAttachment.html
Se corrige la forma de indicar que un campo ```input``` es obligatorio mediante valores de variables. Esto corrige, además, el error generado en **Heroku**, donde la compilación se trababa en el proceso ```htmlmin```, debido a problemas en archivos HTML.
> Utilización de 'ng-required' para campo input

- app/scripts/services/resources/profile.js
Se corrige el URL del **recurso Profile**, que apuntaba incorrectamente a ```/my/profile``` en vez de a ```/profiles/<id>```.
> Corrección en URL de recurso 'Profile'

- Gruntfile.js
- app/scripts/controllers/analyses.js
Se añaden los patrones necesarios para que el proceso ```usemin``` de *Grunt* reemplace las ocurrencias de rutas a imágenes por las correctas **[1]**, ya que el nombre de las mismas es modificado por *Grunt*.
**[1]** https://stackoverflow.com/questions/23919027/how-to-let-grunt-usemin-update-the-js-to-reference-our-revved-images
> Reemplazo de ocurrencia de imágenes en JS con usemin

- app/views/partials/analysis-addAttachment.html
- app/views/partials/analysisform.html
- app/views/partials/config.html
- app/views/partials/groupform.html
- app/views/partials/measurementform.html
- app/views/partials/memberform.html
- app/views/partials/profileform.html
Se reemplazó el texto de los botones *Save* por **Guardar**, en los formularios.
Fixes #91
> Reemplazo de 'Save' por 'Guardar' en formularios

- Gruntfile.js
Se incluye el directorio ```views``` y sus subdirectorios, para que sean **procesados por ```usemin```**, y reemplazar así las rutas a las imágenes cuando se ejecuta ```grunt serve:dist```.
Esto corrige el **error existente en #94**, que no muestra el logo de YesDoc en el navbar de la versión mobile, al ejecutar ```grunt serve:dist```. Esto se debe a que la ruta a la imagen se especifica en un **archivo HTML ubicado en ```views/partials```**.
**Recursos utilizados**:
**[1]** https://stackoverflow.com/questions/20859450/gruntjs-usemin-doesnt-look-in-subfolders
> Inclusión de archivos HTML en 'views/' para Grunt usemin

- Gruntfile.js
Se agregan las **fuentes de Flexslider** al directorio ```dist```, para que funcionen correctamente mediante ```grunt serve:dist```. Debido a que **Flexslider usa rutas relativas** para acceder a sus fuentes, las mismas se agregan al directorio ```dist/styles/fonts```.
Fix #132
> Copia de fuentes de Flexslider en Gruntfile

- app/views/profilemeasurements.html
Se modifica la tabla de mediciones presente en la sección **Resumen**, para que ocupe todo el ancho de página (issue #113). Además, se hace uso de *tablas de Bootstrap*, con cabeceras de columna, condensada y responsiva.
Se quita la columna **Fuente** y el ícono de **Compartir**, que no tenía funcionalidad asociada.
> Modificación de tabla resumen de mediciones

- app/scripts/controllers/analysis-new.js
- app/scripts/controllers/profileinformation.js
- app/styles/main.css
- app/views/partials/analysisform.html
Corrección de error de estilo para mejorar la lista de análisis, esta corrección sirve para que no se vea lo que no cabe del nombre del análisis en la vista previa del mismo. Se añadieron mensajes de confirmación para los eliminar sugerido en issue #84 .
> Mensajes de confirmación al eliminar.

- bower.json
Se configura **Bower**, para que instale la última versión de la rama ```master``` de **angular-flexslider**, y así poder comprobar si se resuelven algunos *issues* relacionados al uso de este paquete.
> Actualización de 'angular-flexslider' al estado de su rama master

- app/views/partials/analysis-addAttachment.html
- app/views/partials/analysisform.html
- app/views/partials/measurementform.html
Se cambia el **formato de fecha**, en aquellos formularios que aún mostraban las fechas como ```yyyy-MM-dd```. El nuevo formato es ```dd-MM-yyyy```.
> Cambio de formato de fecha en formularios

- app/styles/light-bootstrap-dashboard.css
- app/views/partials/analysis-addMeasurement.html
Bootstrap utiliza un color muy claro en sus carteles de alerta, los cuales no se van a ver en la presentación, puedo mantenerlos o utilizar un verde fuerte como el utilizado en la botonera vertical "#5CB85C".
Recomendación dada en el issue #109
> cambio de color del alert

- app/scripts/services/authentication.js
Cada vez que se evalua si el usuario está logueado, se evalua con el token contra la api, esto se realiza una sola vez. 
_Se mejoró ampliamente en el rendimiento_
> Una sola petición a token por necesidad de logueo

- app/styles/main.css
Con overflow el navegador muestra el elemento con la altura necesaria para que sus contenidos se vean completamente.
> Arreglos de la botonera responsive

- app/views/partials/measurementform.html
Se corrige la obtención del ID de MeasurementUnit, en el formulario de mediciones, al navegar correctamente la relación entre la **validación** y la **unidad de medición**.
> Corrección en obtención de ID de MeasurementUnit

- app/views/compartidos.html
Con la última modificación, el mensaje de **seleccionar usuario** no se ocultaba cuando se elegía un usuario.
> Corrección en la ocultación de mensaje cuando se elige un usuario para visualizar análisis
