app/index.html, app/scripts/app.js, app/scripts/controllers/measurement-edit.js, app/scripts/controllers/measurement-new.js, app/scripts/controllers/profilemeasurements.js, app/scripts/services/resources/measurement.js, app/scripts/services/resources/measurementsource.js, app/scripts/services/resources/measurementtype.js, app/scripts/services/resources/measurementunit.js, app/scripts/services/resources/profilemeasurements.js, app/views/measurement-edit.html, app/views/measurement-new.html, app/views/partials/measurementform.html, app/views/profilemeasurements.html, test/spec/controllers/measurement-edit.js, test/spec/controllers/measurement-new.js, test/spec/controllers/profilemeasurements.js
Lista de mediciones de usuario.
=> Generación del perfil de mediciones

app/scripts/controllers/login.js, app/views/login.html
Se generarán los avisos y alertas necesarios relacionados al módulo de logeo
=> Alertas y avisos en el loguin de usuario

app/views/partials/profileform.html, app/views/profileinformation-edit.html, app/views/profileinformation-new.html
…e deshabilitó el input hasta q todos los valores esten correctos
=> Alertas y avisos relacionados a la carga y edición del perfil de usuario

app/scripts/services/resources/measurement.js, app/scripts/services/resources/measurementsource.js, app/scripts/services/resources/measurementtype.js, app/scripts/services/resources/measurementunit.js, app/scripts/services/resources/profile.js, app/scripts/services/resources/profilemeasurements.js
Se corrigieron algunos errores de sintaxis, y se verficó que pasaran los tests
=> [WIP]Fixes on resources

app/scripts/controllers/measurement-new.js, app/views/measurement-edit.html, app/views/measurement-new.html, app/views/partials/measurementform.html
Se generarán los avisos necesarios en los formularios y se corregirán los errores que se detecten.
=> Alertas, avisos y correcciones del módulo de mediciones

app/index.html
Se solucionaron los problemas del navbar no responsive añadiendo propedades de bootstrap.
> navbar-header
> navbar-collapse
=> Navbar responsive

app/scripts/directives/linegraph.js, app/styles/main.css
Se agregaron puntos en los lugares donde hay valores a observar
No se destacan en los ejes todos los valores máxmos y minimos. Salvo el eje Y de la gráfica principal
=> Correcciones visuales de las gráficas

app/scripts/controllers/profileanduser-new.js, app/scripts/controllers/profileinformation-edit.js, app/scripts/services/authentication.js
Cuando se editaba un usuario, y se querían guardar los cambios, estos no eran persistidos en la api. Ahora está corregido. 
También se corrigió el dropdown cuando se quiere crear un nuevo usuario
=> Se persiste la edición del usuario

app/index.html
Se cambia *Perfíl* por *Perfil* en la barra lateral.
=> Corrección de sintaxis en palabra 'Perfil'

app/index.html
Se ubicaron las inclusiones de los nuevos archivos CSS dentro del bloque definido por `````` y ``````. De esta manera, el proceso ```grunt serve:dist``` hace uso de estos archivos al armar el ```main.css``` dentro de la carpeta ```dist```.
=> Reorganización de archivos CSS en index

app/scripts/controllers/analyses.js, app/scripts/controllers/analysesshow.js, app/scripts/controllers/analysis-new.js, app/scripts/controllers/bloodcholesterol.js, app/scripts/controllers/dropbox-auth-finish.js, app/scripts/controllers/dropbox-auth-start.js, app/scripts/controllers/height.js, app/scripts/controllers/login.js, app/scripts/controllers/measurement-edit.js, app/scripts/controllers/measurement-new.js, app/scripts/controllers/profileanduser-new.js, app/scripts/controllers/profileinformation-edit.js, app/scripts/controllers/profileinformation.js, app/scripts/controllers/profilemeasurements.js, app/scripts/controllers/user-new.js, app/scripts/controllers/weight.js, app/scripts/services/authentication.js
Se refactorizo la clase _authorization_ para que _auth.isLogged_ se comporte como un decorador de las funciones de los controladores. Funciona como un wrapper, de esta manera no se ejecuta ningua accion que esté por dentro de la función pasada como argumento a _auth.isLogged_, si el usuario no está logueado.
=> Auth refactor

app/index.html, app/scripts/app.js, app/scripts/controllers/nav.js, app/styles/main.css, app/views/analyses.html, app/views/home.html
Solo se muestran los botones de acceso a información de un usuario en particular cuando el usuario está logueado.
=> Auth view refactor

app/index.html, app/scripts/controllers/analysesshow.js, app/scripts/services/resources/analysiscomments.js, app/views/analyses-show.html
Se implementó el posteo de comentarios
=> Comentarios

app/index.html, app/scripts/app.js, app/scripts/controllers/analyses.js, app/scripts/controllers/analysesshow.js, app/scripts/controllers/nav.js, app/scripts/controllers/notifications.js, app/scripts/services/authentication.js, app/scripts/services/global.js, app/scripts/services/resources/notifications.js, app/styles/light-bootstrap-dashboard.css, app/styles/main.css, app/views/analyses-show.html, app/views/notifications.html, bower.json, test/karma.conf.js
+ Se muestran las notificaciones y se marcan como leidas una vez clickeadas
+ Se muestran las ultimas 20 notificaciones en una nueva vista
+ Se corrigieron errores de fechas
=> Notificaciones

app/scripts/controllers/analyses.js, app/scripts/controllers/analysesshow.js, app/scripts/controllers/nav.js, app/styles/main.css, app/views/analyses-show.html, app/views/partials/measurement_same_type.html
* Se cambió el recurso por el nuevo con autenticación por parametro
* Fixes CSS
=> Thumbnails mejorados

app/index.html
Se añadieron filtros de angular para colorear la opción del navbar donde se encuentra navegando el usuario.
=> Selección del navbar

app/index.html, app/scripts/controllers/analysesshow.js, app/scripts/controllers/dropbox-auth-finish.js, app/scripts/controllers/profileinformation.js, app/scripts/services/resources/mygroupmemberships.js, app/scripts/services/resources/permissions.js, app/views/partials/config.html, app/views/profileinformation.html
* Se muestran las opciones de los grupos segun los permisos.
* Se pueden quitar permisos de un análisis dado
* Fixes CSS
=> Permisos de análisis y grupos

app/views/partials/navbar_options.html
Se cambio el icono de compartición, por uno mas representativo.  Este icono ya estaba, pero en el merge de la botonera vertical lo pise.
=> Cambio del icono de compartición

app/index.html
Uso de ngbind para mostrar la cantidad de notificaciones
=> Corrección de corchetes cuando el cotrolador no carga

app/scripts/controllers/analysesshow.js, app/views/partials/config.html
* Luego de compartir un análisis no se podía recompartirlo __Corregido__
* En el menú de compartir análisis no se mostraba el apellido del usuario __Corregido__
=> Fix share analysis

app/index.html, app/scripts/app.js, app/scripts/controllers/analysis-new.js, app/scripts/controllers/measurement-new.js, app/scripts/services/resources/measurementtypeunit.js, app/views/measurement-edit.html, app/views/measurement-new.html, app/views/partials/measurementform.html, bower.json, test/karma.conf.js
* Se agregó el slider a la vista de nueva medición (En análisis y resumen)
* Se deshabilita el slider y el campo value hasta seleccionar una unidad de medicion
* Se muestra aviso en caso de que el usaurio supere el valor max y minimo devuelto por API
=> Slider medicion

app/scripts/controllers/analysis-new.js, app/views/analysis-new.html, app/views/partials/profileform.html
=> Se vacía el formulario de mediciones al cargar una en el analisis

app/styles/light-bootstrap-dashboard.css, app/styles/main.css
Se van a modificar algunos colores de botones, navbar, letras, etc.
=> Arreglos del css

app/views/login.html
Se cambio el mensaje de validación y el nombre del campo a ser llenado correspondiente al issue #52
=> Mensaje de error incorrecto

app/views/height.html, app/views/home.html
Arreglos en la vista de las gráficas. Cambio de títulos.
=> Cambio de titulos en la vista de las gráficas

app/styles/light-bootstrap-dashboard.css
Se saco la opacidad a las letras del vertical navbar
=> Opacidad letras del vertical navbar

app/views/partials/profileform.html, app/views/profileanduser-new.html, app/views/profileinformation-edit.html
#128 Se pusieron los títulos en las fichas de nuevo usuario y la de  de editar usuario.
=> titulos en ficha de formularios

app/scripts/controllers/analysis-new.js, app/scripts/controllers/measurement-edit.js, app/scripts/controllers/measurement-new.js, app/views/partials/measurementform.html
* Fix issue #130 
* Se aplica el slider a editar medición en resumen
* Se actualiza la lista de unidades de medición al editar
=> Fix issue #130 y se actualiza la lista de unidades de medición al editar

app/scripts/controllers/profileanduser-new.js, app/styles/light-bootstrap-dashboard.css, app/views/partials/measurementform.html, app/views/partials/profileform.html, app/views/profileanduser-new.html
Se corrigió el error nombrado en el issue #50 y #127
=> Corrección del Issue #50

app/index.html, app/scripts/controllers/analysesshow.js, app/scripts/controllers/profileinformation.js, app/scripts/services/resources/mygravatar.js, app/scripts/services/resources/profile.js, app/styles/animate.css, app/styles/main.css, app/views/analyses-show.html, app/views/profileinformation.html
* Gravatars en notificaciones e información del perfil
* Cambio de efecto para ng-show y ng-hide
=> Imagenes personales

app/scripts/controllers/profileinformation.js, app/views/analyses-show.html, app/views/profileinformation.html
* Creación de objeto por defecto en profileInformation, lo que evitaría multiples errores en la vista al querér mostrar datos que pertenecen a un objeto inexistente.
* Se cambia src por ng-src porque al descargar la imagen toma el efecto fadein
=> Creación de objecto por defecto en profileInformation y carga de imagenes con ng-src

app/index.html, app/styles/light-bootstrap-dashboard.css, app/styles/main.css, app/views/partials/vertical_navbar.html
Para distinguir a los médicos del usuario común se cambia, a azul, el color de la botonera.
Este color solo se presenta cuando el usuario logueado se ha registrado como médico, en los demás casos continua siendo de color verde.
=> Botonera médico

app/index.html, app/scripts/app.js, app/scripts/controllers/messages.js, app/scripts/controllers/nav.js, app/scripts/controllers/notifications.js, app/views/notifications.html
Ya se muestran los mensajillos por separadillo.
=> Mensajes separados de las notificaciones

app/scripts/controllers/analysesshow.js, app/scripts/controllers/analysis-new.js, app/scripts/services/resources/analysisfile.js, app/views/analyses-show.html
Se incorpora a la vista del análisis:
* Eliminar archivos.
* Agregar un archivo al analisis.
* Agregar una nueva Medición.
=> Eliminar archivos, agregar mediciones y agregar archivos

app/scripts/controllers/profileinformation.js, app/views/partials/groupform.html, app/views/partials/memberform.html
* Se implemento la posibilidad de crear un nuevo tipo de membresía desde agregar grupo
* Se implemento la posibilidad de crear un nuevo tipo de membresía desde agregar un nuevo Miembro
=> Permissions new

app/dropbox-auth-finish.html, app/scripts/controllers/analysis-new.js, app/scripts/controllers/login.js, app/views/login.html
Se cambian las rutas inicializadas con ```/#/```, por ```#/```. Esto se debe a que **Ionic** genera error cuando no se cumple que las rutas comiencen con este patrón.
=> Corrección de rutas inicializadas con '/#/'

app/views/analyses-show.html, app/views/analyses.html, app/views/compartidos.html, app/views/profileinformation.html
Se corrige el **formato de fechas**, para mostrar las mismas como ```dd-MM-yyyy```.
=> Corrección de formato de fechas

app/index.html, app/scripts/app.js, app/scripts/controllers/compartidos.js, app/scripts/controllers/patients.js, app/views/compartidos.html, app/views/partials/navbar_options.html, app/views/patients.html
Se le muestra a los médicos los pacientes que le han compartido sus análisis.
Además a partir de esta lista puede ir a ver los análisis compartidos. 
En los análisis compartidos se le muestra el nombre del dueño de esos análisis.
=> Vista de Pacientes para médicos

app/views/partials/profileform.html, app/views/profileanduser-new.html
Se mejora la interfaz del **formulario "Nuevo perfil"**. **Se adjunta imagen.**
=> Edición del formulario de 'Nuevo perfil'

app/views/login.html
Se mejoró la presentación del **formulario de login**. **Se adjunta imagen.**
=> Edición del formulario de login

app/views/profilemeasurements.html
Se edita la **tabla resumen de mediciones**.
* En la columna **Análisis**, los enlaces a análisis se muestran en color azul. Aquellas mediciones sin análisis asociado, muestran la fuente del mismo.
* El botón **Nuevo** se muestra en color verde.
* Se añade la acción **Ver gráfica**, a la columna de **Acciones**.
=> Edición de tabla resumen de mediciones

app/index.html, app/scripts/app.js, app/scripts/controllers/shared-graphs.js, app/scripts/services/resources/profilemeasurements2.js, app/views/partials/navbar_options.html, app/views/shared-graphs.html
Se añade la vista de **Gráficas**, que le permite a un médico visualizar las gráficas de sus pacientes, al seleccionar su nombre y el tipo de medición a visualizar.
=> Visualización de gráficas de pacientes, para médicos

app/styles/light-bootstrap-dashboard.css, app/views/analyses-show.html, app/views/analyses.html, app/views/compartidos.html, app/views/home.html, app/views/profileinformation.html, app/views/shared-graphs.html
* Se corrige el error por el cual no se veían los dropdowns(overflow:hidden)
* Se corrige el error de salida de botones del titulo contenedor, a través del uso de clearfix, cuando el boton se encuentra flotando.
* Se agregan tablas responsives
=> No overflow hidden

bower.json
Se fuerza la instalación y actualizacion de angular , para que no genere conflicto en el deploy en heroku
=> angular force install
